//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zdjecia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zdjeciatb
    {
        public int id { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> daata { get; set; }
        public string sciezka { get; set; }
    }
}
